/*
 * fetch-prices.js — fetches current Amazon.in prices for neoKesan products and
 * writes them to assets/live-prices.js (the single source of truth the site reads).
 *
 * Run: node scripts/fetch-prices.js
 * Runs on a schedule via .github/workflows/update-prices.yml (and manually).
 *
 * On any failure for a product (HTTP error / bot-block / no price found) it keeps
 * the previous value already in live-prices.js, so the site never shows a blank
 * or null price.
 */
const fs = require('fs');
const path = require('path');

const OUT_FILE = path.join(__dirname, '..', 'assets', 'live-prices.js');

const PRODUCTS = [
  { key: 'ponic', asin: 'B0HBX6WPTL', url: 'https://www.amazon.in/dp/B0HBX6WPTL' },
  { key: 'bloom', asin: 'B0HBWZ4G26', url: 'https://www.amazon.in/dp/B0HBWZ4G26' },
  { key: 'folix', asin: 'B0HBXB8TQ9', url: 'https://www.amazon.in/dp/B0HBXB8TQ9' },
];

// Browser-like headers that get past Amazon's bot detection (verified via curl).
const HEADERS = {
  'User-Agent':
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
    '(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
  'Accept-Language': 'en-IN,en;q=0.9,hi-IN;q=0.8,en-GB;q=0.7',
  'Referer': 'https://www.google.com/',
  'Cache-Control': 'no-cache',
  'Pragma': 'no-cache',
};

const MAX_RETRIES = 3;
const RETRY_DELAY_MS = 2000;

function readCurrentPrices() {
  try {
    const src = fs.readFileSync(OUT_FILE, 'utf8');
    const match = src.match(/NEOKESAN_PRICES\s*=\s*(\{.*?\})/);
    if (match) return JSON.parse(match[1].replace(/([{,]\s*)([a-zA-Z0-9_]+)\s*:/g, '$1"$2":'));
  } catch (_) {
    // no file yet — fresh seed below
  }
  return null;
}

// Structured value in Amazon's buybox JSON; round to whole rupees (₹679, not 679.00).
function parseStructured(html) {
  const m = html.match(/"priceAmount":(\d+(?:\.\d+)?)/);
  return m ? Math.round(parseFloat(m[1])) : null;
}

// Visible price fallback: <span class="a-price-whole">679</span>
function parseVisible(html) {
  const m = html.match(/class="a-price-whole">([\d,]+)/);
  return m ? parseInt(m[1].replace(/,/g, ''), 10) : null;
}

async function fetchWithRetry(url) {
  let lastErr;
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const res = await fetch(url, { headers: HEADERS });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const html = await res.text();
      const price =
        parseStructured(html) ||
        parseVisible(html) ||
        (() => { throw new Error('no price found in page'); })();
      return price;
    } catch (err) {
      lastErr = err;
      console.warn(`  attempt ${attempt}/${MAX_RETRIES} failed: ${err.message}`);
      if (attempt < MAX_RETRIES) {
        await new Promise((r) => setTimeout(r, RETRY_DELAY_MS));
      }
    }
  }
  throw lastErr;
}

async function main() {
  const prev = readCurrentPrices() || {};
  const out = {};
  for (const p of PRODUCTS) {
    process.stdout.write(`Fetching ${p.key} (${p.asin})... `);
    try {
      const price = await fetchWithRetry(p.url);
      out[p.key] = price;
      console.log(`₹${price}`);
    } catch (err) {
      const kept = prev[p.key];
      console.log(`FAILED (${err.message}) — keeping previous ₹${kept ?? 'n/a'}`);
      if (kept == null) {
        console.error(`  No previous price for "${p.key}" and fetch failed; skipping write.`);
        process.exitCode = 1;
      } else {
        out[p.key] = kept;
      }
    }
  }

  // Preserve keys even if some product silently produced nothing above.
  for (const p of PRODUCTS) {
    if (out[p.key] == null && prev[p.key] != null) out[p.key] = prev[p.key];
  }

  const lines = [
    '/* Auto-generated by scripts/fetch-prices.js — do not edit by hand. */',
    `window.NEOKESAN_PRICES = ${JSON.stringify(out, null, 2).replace(/\n/g, '\n')};`,
    '',
  ];
  fs.writeFileSync(OUT_FILE, lines.join('\n'));
  console.log(`\nWrote ${path.relative(process.cwd(), OUT_FILE)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
